config/routes.rb
Iimbvista2015::Application.routes.draw do
  resources :items

  resources :products

  resources :schedule_items

  get "shop_at_vista/index"

  get "shop_at_vista/checkout"

  get "shop_at_vista/payment_complete"

  post "shop_at_vista/payment_success"

  get "shop_at_vista/save_address"

  get "shop_at_vista/product_info/:id", :controller => "shop_at_vista", :action => "product_info"
 
  get "shop_at_vista/add_to_cart"
  
  get "shop_at_vista/remove_from_cart"
  
  get "api/auth_user"

  get "dashboard/index"
  
  get "dashboard/event_registrations/:id", :controller => "dashboard", :action => "event_registrations"

  get "dashboard/college_registrations/:id", :controller => "dashboard", :action => "college_registrations"

  resources :bulletins

  post "registrations/register"

  get "myevents/home"

  get "myevents/information/:id", :controller => "myevents", :action => "information"

  resources :event_tabs

  resources :events

  resources :event_categories

  get "events/for_event_category/:id", :controller => "events", :action => "for_event_category"
  
  get "event_tabs/for_event/:id", :controller => "event_tabs", :action => "for_event"

  get "events/my_events"
  
  get "backend/index"

  devise_for :users

  get "home/index"

  get "home/acco_n_travel"

  get "home/schedule"

  root :to => 'home#index'

end

app/models/event_category.rb
class EventCategory < ActiveRecord::Base
	default_scope where(:active => true)

  attr_accessible :title, :description, :active

  has_many :events
  has_and_belongs_to_many :users
end

app/controllers/event_categories_controller.rb
class EventCategoriesController < ApplicationController
  # GET /event_categories
  # GET /event_categories.json

  before_filter :check_permission

  def check_permission
     authorize! :manage, EventCategory
  end

  def index
    if current_user.is_super_admin?
      @event_categories = EventCategory.unscoped.all
    elsif
      redirect_to events_my_events_path
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @event_categories }
    end
  end

  # GET /event_categories/1
  # GET /event_categories/1.json
  def show
    @event_category = EventCategory.unscoped.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event_category }
    end
  end

  # GET /event_categories/new
  # GET /event_categories/new.json
  def new
    @event_category = EventCategory.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event_category }
    end
  end

  # GET /event_categories/1/edit
  def edit
    @event_category = EventCategory.unscoped.find(params[:id])
  end

  # POST /event_categories
  # POST /event_categories.json
  def create
    @event_category = EventCategory.new(params[:event_category])

    respond_to do |format|
      if @event_category.save
        format.html { redirect_to @event_category, notice: 'Event category was successfully created.' }
        format.json { render json: @event_category, status: :created, location: @event_category }
      else
        format.html { render action: "new" }
        format.json { render json: @event_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /event_categories/1
  # PUT /event_categories/1.json
  def update
    @event_category = EventCategory.unscoped.find(params[:id])

    respond_to do |format|
      if @event_category.update_attributes(params[:event_category])
        format.html { redirect_to @event_category, notice: 'Event category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event_categories/1
  # DELETE /event_categories/1.json
  def destroy
    @event_category = EventCategory.unscoped.find(params[:id])
    @event_category.destroy

    respond_to do |format|
      format.html { redirect_to event_categories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/event_categories_helper.rb
module EventCategoriesHelper
end

app/views/event_categories/_form.html.erb
<%= form_for(@event_category) do |f| %>
  <% if @event_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event_category.errors.count, "error") %> prohibited this event_category from being saved:</h2>

      <ul>
      <% @event_category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/event_categories/edit.html.erb
<h1>Editing event_category</h1>

<%= render 'form' %>

<%= link_to 'Show', @event_category %> |
<%= link_to 'Back', event_categories_path %>

app/views/event_categories/index.html.erb
<h1>Listing event_categories</h1>
<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <% @event_categories.each do |event_category| %>  
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingOne">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion" <%= "href='#collapse#{event_category.id}'" %> aria-expanded="true" <%= "aria-controls='collapse#{event_category.id}'" %>>
          <%= event_category.title %>
        </a>
      </h4>
    </div>
    <div <%= "id='collapse#{event_category.id}'" %> class="panel-collapse collapse" role="tabpanel" <%= "aria-labelledby='heading#{event_category.id}'" %> >
      <div class="panel-body">
        <p class="well"><b>Description</b><br/>
        <%= event_category.description.html_safe %></p>
        <p><b>Active</b><br/>
        <%= event_category.active %></p>
        <p><%= link_to 'Events', "/events/for_event_category/#{event_category.id}", class: "btn btn-default" %>
        <%= link_to 'Show', event_category, class: "btn btn-default" %>
        <%= link_to 'Edit', edit_event_category_path(event_category), class: "btn btn-default" %>
        <%= link_to 'Destroy', event_category, confirm: 'Are you sure?', method: :delete, class: "btn btn-default" %></p>
      </div>
    </div>
  </div>
  <% end %>
</div>

<%= link_to 'New Event category', new_event_category_path, class: "btn btn-warning" %>

app/views/event_categories/new.html.erb
<h1>New event_category</h1>

<%= render 'form' %>

<%= link_to 'Back', event_categories_path %>

app/views/event_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @event_category.title %>
</p>

<p>
  <b>Description:</b>
  <div class="well"><%= @event_category.description.html_safe %></div>
</p>

<p>
  <b>Active:</b>
  <%= @event_category.active %>
</p>


<%= link_to 'Edit', edit_event_category_path(@event_category) %> |
<%= link_to 'Home', "/backend/index" %>