config/routes.rb
Iimbvista2015::Application.routes.draw do
  resources :items

  resources :products

  resources :schedule_items

  get "shop_at_vista/index"

  get "shop_at_vista/checkout"

  get "shop_at_vista/payment_complete"

  post "shop_at_vista/payment_success"

  get "shop_at_vista/save_address"

  get "shop_at_vista/product_info/:id", :controller => "shop_at_vista", :action => "product_info"
 
  get "shop_at_vista/add_to_cart"
  
  get "shop_at_vista/remove_from_cart"
  
  get "api/auth_user"

  get "dashboard/index"
  
  get "dashboard/event_registrations/:id", :controller => "dashboard", :action => "event_registrations"

  get "dashboard/college_registrations/:id", :controller => "dashboard", :action => "college_registrations"

  resources :bulletins

  post "registrations/register"

  get "myevents/home"

  get "myevents/information/:id", :controller => "myevents", :action => "information"

  resources :event_tabs

  resources :events

  resources :event_categories

  get "events/for_event_category/:id", :controller => "events", :action => "for_event_category"
  
  get "event_tabs/for_event/:id", :controller => "event_tabs", :action => "for_event"

  get "events/my_events"
  
  get "backend/index"

  devise_for :users

  get "home/index"

  get "home/acco_n_travel"

  get "home/schedule"

  root :to => 'home#index'

end

app/models/item.rb
class Item < ActiveRecord::Base

	attr_accessible :sku, :product_id, :price, :item_desc, :available

	belongs_to :product
	has_and_belongs_to_many :carts
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # GET /items
  # GET /items.json
  before_filter :authenticate

  def authenticate
    unless user_signed_in? && (current_user.is_super_admin? || current_user.is_vendor?)
      redirect_to root_path
    end
  end

  def available_items
    if user_signed_in? && current_user.is_super_admin?
      Item.all
    else
      Item.all.select{|it| it.product.user_id==current_user.id}
    end
  end

  def index
    @items = available_items

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @item = Item.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render json: @item, status: :created, location: @item }
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sku %><br />
    <%= f.text_field :sku %>
  </div>
  <div class="field">
    <%= f.label :product_id %><br />
    <%= f.number_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :item_desc %><br />
    <%= f.text_field :item_desc %>
  </div>
  <div class="field">
    <%= f.label :available %><br />
    <%= f.number_field :available %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>Listing items</h1>

<table border=1 class="table table-striped" width="100%">
  <tr>
    <th>Sku</th>
    <th>Product</th>
    <th>Price</th>
    <th>Item desc</th>
    <th>Available</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @items.each do |item| %>
  <tr>
    <td><%= item.sku %></td>
    <td><%= item.product.name %></td>
    <td><%= item.price %></td>
    <td><%= item.item_desc %></td>
    <td><%= item.available %></td>
    <td><%= link_to 'Show', item %></td>
    <td><%= link_to 'Edit', edit_item_path(item) %></td>
    <td><%= link_to 'Destroy', item, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Item', new_item_path %>
<br/><br/>
<%= link_to 'Products', products_path %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Sku:</b>
  <%= @item.sku %>
</p>

<p>
  <b>Product:</b>
  <%= @item.product_id %>
</p>

<p>
  <b>Price:</b>
  <%= @item.price %>
</p>

<p>
  <b>Item desc:</b>
  <%= @item.item_desc %>
</p>

<p>
  <b>Available:</b>
  <%= @item.available %>
</p>


<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>