config/routes.rb
Iimbvista2015::Application.routes.draw do
  resources :items

  resources :products

  resources :schedule_items

  get "shop_at_vista/index"

  get "shop_at_vista/checkout"

  get "shop_at_vista/payment_complete"

  post "shop_at_vista/payment_success"

  get "shop_at_vista/save_address"

  get "shop_at_vista/product_info/:id", :controller => "shop_at_vista", :action => "product_info"
 
  get "shop_at_vista/add_to_cart"
  
  get "shop_at_vista/remove_from_cart"
  
  get "api/auth_user"

  get "dashboard/index"
  
  get "dashboard/event_registrations/:id", :controller => "dashboard", :action => "event_registrations"

  get "dashboard/college_registrations/:id", :controller => "dashboard", :action => "college_registrations"

  resources :bulletins

  post "registrations/register"

  get "myevents/home"

  get "myevents/information/:id", :controller => "myevents", :action => "information"

  resources :event_tabs

  resources :events

  resources :event_categories

  get "events/for_event_category/:id", :controller => "events", :action => "for_event_category"
  
  get "event_tabs/for_event/:id", :controller => "event_tabs", :action => "for_event"

  get "events/my_events"
  
  get "backend/index"

  devise_for :users

  get "home/index"

  get "home/acco_n_travel"

  get "home/schedule"

  root :to => 'home#index'

end

app/models/schedule_item.rb
class ScheduleItem < ActiveRecord::Base
end

app/controllers/schedule_items_controller.rb
class ScheduleItemsController < ApplicationController

  before_filter :validate_user

  def validate_user
    if user_signed_in? && current_user.is_super_admin?
    else
      redirect_to root_path
    end
  end
  # GET /schedule_items
  # GET /schedule_items.json
  def index
    @schedule_items = ScheduleItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @schedule_items }
    end
  end

  # GET /schedule_items/1
  # GET /schedule_items/1.json
  def show
    @schedule_item = ScheduleItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @schedule_item }
    end
  end

  # GET /schedule_items/new
  # GET /schedule_items/new.json
  def new
    @schedule_item = ScheduleItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @schedule_item }
    end
  end

  # GET /schedule_items/1/edit
  def edit
    @schedule_item = ScheduleItem.find(params[:id])
  end

  # POST /schedule_items
  # POST /schedule_items.json
  def create
    @schedule_item = ScheduleItem.new(params[:schedule_item])

    respond_to do |format|
      if @schedule_item.save
        format.html { redirect_to @schedule_item, notice: 'Schedule itpem was successfully created.' }
        format.json { render json: @schedule_item, status: :created, location: @schedule_item }
      else
        format.html { render action: "new" }
        format.json { render json: @schedule_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /schedule_items/1
  # PUT /schedule_items/1.json
  def update
    @schedule_item = ScheduleItem.find(params[:id])

    respond_to do |format|
      if @schedule_item.update_attributes(params[:schedule_item])
        format.html { redirect_to @schedule_item, notice: 'Schedule itpem was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @schedule_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedule_items/1
  # DELETE /schedule_items/1.json
  def destroy
    @schedule_item = ScheduleItem.find(params[:id])
    @schedule_item.destroy

    respond_to do |format|
      format.html { redirect_to schedule_items_url }
      format.json { head :no_content }
    end
  end
end

app/views/schedule_items/_form.html.erb
<%= form_for(@schedule_item) do |f| %>
  <% if @schedule_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@schedule_item.errors.count, "error") %> prohibited this schedule_item from being saved:</h2>

      <ul>
      <% @schedule_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :event_start %><br />
    <%= f.datetime_select :event_start %>
  </div>
  <div class="field">
    <%= f.label :event_end %><br />
    <%= f.datetime_select :event_end %>
  </div>
  <div class="field">
    <%= f.label :venue %><br />
    <%= f.text_field :venue %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schedule_items/edit.html.erb
<h1>Editing schedule_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @schedule_item %> |
<%= link_to 'Back', schedule_items_path %>

app/views/schedule_items/index.html.erb
<h1>Listing schedule_items</h1>

<table border=1 class="table table-striped" width="100%">
  <tr>
    <th>Description</th>
    <th>Event start</th>
    <th>Event end</th>
    <th>Venue</th>
    <th>Show</th>
    <th>Edit</th>
    <th>Destroy</th>
  </tr>

<% @schedule_items.each do |schedule_item| %>
  <tr>
    <td><%= schedule_item.description %></td>
    <td><%= schedule_item.event_start.strftime("%d-%m-%Y %I:%M%p") %></td>
    <td><%= schedule_item.event_end.strftime("%d-%m-%Y %I:%M%p") %></td>
    <td><%= schedule_item.venue %></td>
    <td><%= link_to 'Show', schedule_item %></td>
    <td><%= link_to 'Edit', edit_schedule_item_path(schedule_item) %></td>
    <td><%= link_to 'Destroy', schedule_item, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Schedule item', new_schedule_item_path %>

app/views/schedule_items/new.html.erb
<h1>New schedule_item</h1>

<%= render 'form' %>

<%= link_to 'Back', schedule_items_path %>

app/views/schedule_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @schedule_item.description %>
</p>

<p>
  <b>Event start:</b>
  <%= @schedule_item.event_start.strftime("%d-%m-%Y %I:%M%p") %>
</p>

<p>
  <b>Event end:</b>
  <%= @schedule_item.event_end.strftime("%d-%m-%Y %I:%M%p") %>
</p>

<p>
  <b>Venue:</b>
  <%= @schedule_item.venue %>
</p>


<%= link_to 'Edit', edit_schedule_item_path(@schedule_item) %> |
<%= link_to 'Back', schedule_items_path %>