config/routes.rb
Iimbvista2015::Application.routes.draw do
  resources :items

  resources :products

  resources :schedule_items

  get "shop_at_vista/index"

  get "shop_at_vista/checkout"

  get "shop_at_vista/payment_complete"

  post "shop_at_vista/payment_success"

  get "shop_at_vista/save_address"

  get "shop_at_vista/product_info/:id", :controller => "shop_at_vista", :action => "product_info"
 
  get "shop_at_vista/add_to_cart"
  
  get "shop_at_vista/remove_from_cart"
  
  get "api/auth_user"

  get "dashboard/index"
  
  get "dashboard/event_registrations/:id", :controller => "dashboard", :action => "event_registrations"

  get "dashboard/college_registrations/:id", :controller => "dashboard", :action => "college_registrations"

  resources :bulletins

  post "registrations/register"

  get "myevents/home"

  get "myevents/information/:id", :controller => "myevents", :action => "information"

  resources :event_tabs

  resources :events

  resources :event_categories

  get "events/for_event_category/:id", :controller => "events", :action => "for_event_category"
  
  get "event_tabs/for_event/:id", :controller => "event_tabs", :action => "for_event"

  get "events/my_events"
  
  get "backend/index"

  devise_for :users

  get "home/index"

  get "home/acco_n_travel"

  get "home/schedule"

  root :to => 'home#index'

end

app/models/product.rb
class Product < ActiveRecord::Base

	attr_accessible :name, :description, :user_id, :avatar

	mount_uploader :avatar, AvatarUploader

	has_many :items
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  before_filter :authenticate

  def authenticate
    unless user_signed_in? && (current_user.is_super_admin? || current_user.is_vendor?)
      redirect_to root_path
    end
  end

  def available_products
    if user_signed_in? && current_user.is_super_admin?
      Product.all
    else
      Product.where(user_id: current_user.id)
    end
  end

  def index
    @products = available_products

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :avatar %><br />
    <%= f.file_field :avatar %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.hidden_field :user_id, :value => current_user.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table border=1 class="table table-striped" width="100%">
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.name %></td>
    <td><%= product.description %></td>
    <td><%= link_to 'Show', product %></td>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Destroy', product, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product', new_product_path %>
<br/><br/>
<%= link_to 'Items', items_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @product.name %>
</p>

<p>
  <b>Description:</b>
  <%= @product.description %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>